name: Pre-commit checks

on:
  push:
    branches:
      - "build-images"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: .go_version
      - name: Check license
        run: make license-check
      - name: Go lint
        run: make lint
      - name: Run Version Check
        run: make pseudo
      - name: Run build
        run: make image DOCKER_ARCH=amd64 REGISTRY=gresearch VERSION=latest
      - name: List images
        run: docker images