name: Canary

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    environment: canary
    strategy:
      matrix:
        arch: [ amd64, arm64 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract Go Version
        id: get-go-version
        run: |
          GO_VERSION=$(go mod edit -json | jq -r '.Go')
          echo "GO_VERSION=$GO_VERSION" >> $GITHUB_ENV

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Extract version
        id: get_version
        run: echo "VERSION=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Run build
        run: make image DOCKER_ARCH=${{ matrix.arch }} REGISTRY=gresearch VERSION=${{ steps.get_version.outputs.VERSION }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push to Docker Hub
        run: docker images | grep 'gresearch/yunikorn' | awk '{print $1":"$2}' | xargs -I {} sh -c 'docker push {}'
