name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    environment: release
    if: startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/checkout@v4
        with:
          fetch-tags: 1

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: .go_version

      - name: Run build
        run: make image REGISTRY=gresearch VERSION=${{ github.ref }}


      - name: List images
        run: docker images

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push to Docker Hub
        run: docker images | grep 'gresearch/yunikorn' | awk '{print $1":"$2}' | xargs -I {} sh -c 'docker push {}'
